config/routes.rb
Rails.application.routes.draw do
  root controller: :messages, action: :index

  resources :messages
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :deleted_by_user, class_name: 'User', optional: true
  belongs_to :receiving_user, class_name: 'User', optional: true

  delegate :username, :color, to: :user

  scope :viewable, ->(user_id) { where(receiving_user_id: [nil, user_id]).or(where(user_id: user_id)).not_deleted }

  scope :not_deleted, -> { where(deleted_by_user_id: nil) }

  def destroy(user)
    update!(deleted_by_user: user)
  end

  def can_delete?(user)
    user.admin? || self.user == user
  end

  def as_json(options)
    super(options).merge(username: username, color: color, receiving_username: receiving_user&.username)
  end

  def dm?
    ! receiving_user_id.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages

  after_create :set_color

  private

  def set_color
    update color: ColorGenerator.new(lightness: 0.3, seed: id).create_hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include MessagesHelper

  before_action :load_message, only: [:destroy]

  MESSAGE_DISPLAY_DEFAULT = 20

  def index
    @messages = Message.viewable(current_user.id).last(MESSAGE_DISPLAY_DEFAULT)
  end

  def create
    message_data = handle_message(message_body)

    if message_data
      @message = Message.create!(
        {user: current_user}.merge(message_data)
      )

      ChatChannel.broadcast_to "chat", @message
    end
  end

  def destroy
    if current_user.admin? || current_user == @message.user
      DestroyChannel.broadcast_to "destroy", @message
      @message.destroy(current_user)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_body
    message_params["body"]
  end

  def load_message
    @message = Message.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def handle_message(message_body)
    if message_body[0..2] == "/dm"
      _, username, *dm_text = message_body.split(" ")
      dm_text = dm_text.join(" ")
      {
        receiving_user: User.find_by(username: username),
        body: dm_text
      }
    elsif message_body[0] != "/"
      { body: message_body }
    else
      nil
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socket Chatter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <section class="section">
      <div class="containter">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/messages/_form.html.haml
= form_for Message.new, remote: true do |f|
  .columns
    .column.is-four-fifths
      .field
        .control
          = f.text_field :body, placeholder: 'Type here...', class: 'input'
    .column= f.submit class: 'button'

app/views/messages/_message_template.html.haml
#message-template{'style' => 'display: none'}
  .chat-message-containter#id-placeholder
    %span#message-username
    %span#message-recipient
    %span= ": "
    %span#message-body
    %span.is-pulled-right= link_to "✖︎", message_path(0), method: :delete, remote: true

app/views/messages/_messages.html.haml
- messages.each do |message|
  .chat-message-containter{"id" => "msg-id-#{message.id}"}
    %span#message-username{"style" => "color: ##{message.user.color}"}= message.username
    - if message.receiving_user_id
      %span#message-recipient= " → #{message.receiving_user.username}"
    %span= ": "
    %span#message-body= message.body
    - if message.can_delete?(current_user)
      %span.is-pulled-right= link_to "✖︎", message_path(message), method: :delete, remote: true

app/views/messages/index.html.haml
%h1.title Welcome!

.logout.is-pulled-right= link_to "Log Out", destroy_user_session_path, method: :delete

.columns
  .column

  .column.is-two-thirds
    .chat-window= render 'messages', messages: @messages
    = render 'form'
  .column

= render 'message_template'